### ISSUE TITLE
Cannot read property 'isInitialized' of undefined

### ISSUE THREAD

**Issue by JBird608** [TWOverflow/twoverflow.github.io#1]
Hi, 

There looks to be a issues, this started today. 
 
<img width="1440" alt="screen shot 2018-08-09 at 19 17 21" src="https://user-images.githubusercontent.com/1952494/43917739-fda664e0-9c08-11e8-9553-f1865416a729.png">

**Comment by ivanthz** [comment]
It's here too

**Comment by mafrazz** [comment]
Fixed.
